language: go
go:
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - tip
install:
  - go get -v .
script:
  - cd example
  - cp sevensummits.go expect.go
  - bash -ex build.sh
  - cmp sevensummits.go expect.go
